### ISSUE TITLE
Trying to use with create-next-app generated app

### ISSUE THREAD

**Issue by Vaelek** [sculptui/vscode#4]
I have not been able to get this to work. I am using NextJS via create-next-app. 

**To Reproduce**
1. npx create-next-app
2. Click on Start SculptUI

```
Sculpt starting using next
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'next/dist/next-server/server/config'
Require stack:
- F:\Code\testing\nextest\noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at resolveFileName (c:\Users\jim\.vscode\extensions\ardevia.sculptui-vscode-0.7.1\node_modules\resolve-from\index.js:29:39)    
    at resolveFrom (c:\Users\jim\.vscode\extensions\ardevia.sculptui-vscode-0.7.1\node_modules\resolve-from\index.js:43:9)
    at Object.module.exports [as default] (c:\Users\jim\.vscode\extensions\ardevia.sculptui-vscode-0.7.1\node_modules\resolve-from\index.js:46:47)
    at nextPath (c:\Users\jim\.vscode\extensions\ardevia.sculptui-vscode-0.7.1\node_modules\@sculpt-ui\server\lib\scripts\providers\next\server.js:12:66)
    at Object.<anonymous> (c:\Users\jim\.vscode\extensions\ardevia.sculptui-vscode-0.7.1\node_modules\@sculpt-ui\server\lib\scripts\providers\next\server.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'F:\\Code\\testing\\nextest\\noop.js' ]
```

If I follow the custom script steps and add this to my package.json scripts
`"sculpt": "concurrently \"yarn dev\" sculpt"`
I then get

```
Sculpt starting using "npm run sculpt"

> nextest@0.1.0 sculpt
> concurrently "yarn dev" sculpt

[1] 'sculpt' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] sculpt exited with code 1
yarn run v1.15.2
$ next dev -p 30000
[0] ready - started server on 0.0.0.0:30000, url: http://localhost:30000
```

Thanks in advance! I really want to give this a shot.

**Comment by DanyWyss** [comment]
We are looking into this.
Seems newest version of nextjs has another structure of package and some files could not be resolved. Will keep you posted.
